#+title: Socket
#+author: devlift
#+date: <2023-11-17 Fri 21:37>
* Can someone explain how sockets really work? (Network, Operating System, System Calls)
Ok, what is a socket? I learned that is a IP address combined with a PORT
number but this information is too abstract for my taste, I want to go deeper,
so what is really a socket?

Please correct me if you see something wrong here:

Operating System is the big boss in a computer, he manages fkin everything,
processes, memory, I/O devices.

Operating System provides many services to the processes.

These services can be accessesd only with these so called "system calls",
which are an interface between a process and a Operating System service.

sockets() is a system call which enables network communication.

I was just thinking, isn't this socket just a file created by the Operating
System? And somehow this file can receive packets from the internet?

Because I can read and write files very easy, it's just another system call
(File Management Service) and it would make absolute sense!

And considering that the Operating System has this *Process Control Block*,
which is a big table where it stores all the information about all processes
(including Process ID), then I believe it should be easy to link this file to
the process that created this file and voila, I can receive message from the
internet... from a "special file" ... is it true or false?

-----

an IP address is a code which identifies each individual network-attached
device. a port is a number which further differentiates, so that each device
can communicate with multiple separate devices simultaneously and
asynchronously. server programs typically have a set of public IPs and well
known port(s) available.

a socket is a programming abstraction which allows 2 points on a network to
communicate with each other using IP and port (technically, two IPs and two
ports: one of each for each side of the connection). once you specify the IP +
port, and if the other end is waiting for that, then communication over a
network socket is very much like reading or writing to a file.

in unix, "everything is a file" but for networks, the socket connection needs
to specify the IP and port; those do not come from filenames nor from file
data. once the socket is connected, there are ways that you can do file-like
or file-based programming to communicate over the socket.

#+begin_quote
ok but what exactly is this programming abstraction? What does the Operating
System create when you are making that socket() call? Is it a file? Is is a
horse? Is it a penguin? what is it?
#+end_quote

#+begin_quote
the abstraction which C makes available is just an integer. the OS maintains
an array of  sockets, and returns a reference to the one which you create. in
C, the =socket= call returns an integer, which is an index in a list that the OS
maintains. that same OS list also include files. the =socket= call's integer is
also known as a 'file descriptor'; this same type and abstraction which *nix
uses for typical file i/o. in C, if you want to =read/write= from a file, you
call a certain function and pass in an integer (aka "the file
descriptor"). these functions also accept a =socket='s "file" descriptor, and
the OS would then =read/write= across a network.
#+end_quote

-----

Consider an analogy of a family living in a house, the house's mailing address
is like the "ip address". the mailman brings any letter thats addressed to the
ip address to that house.

The port is like the name written on the envelope, above the street address,
it distinguishes between the individuals who live at that address.

The socket is a combination of both the source's IP+port, and the
destination's IP+port. A socket is like an envelope that contains both the
target's address and the sender's return address.

[[https://www.reddit.com/r/eli5_programming/comments/15wpdh0/can_someone_explain_how_sockets_really_work/]]
-----
* Questions about binding in sockets programming
When do I need to use =bind()=? When does the kernel automatically do that, and
when do I need to do it manually?

What does it exactly do? I hear people saying that it associates a socket with
a port number, but what does that exactly mean?

Who do I bind? The client or the server?

---

Server binds to get a specific port. So e.g. ssh server binds port 22, and
every client that wants to connect knows they must connect to port 22.

Client automatically binds any free port because you, as a client do, not care
which port is used oin your computer to communicate with the ssh server. And
when you connect to the server, you send also your port number so that the
server knows to which to answer.

---

Sockets may also be bound to a specific local address. This is commonly used
to force the process to communicate through a specific network adapter on
multi-homed machines. Similarly, binding to 127.0.0.1 is used to restrict
access to the socket to local processes only.

---

A client most likely =bind()= when a system has multiple IP addresses, to choose
which one to connect over. Usually this is not necessary, but in certain cases
it may be beneficial. Usually in these cases 0 is passed as port, and the
kernel will use a free port.

Similarly server sockets can use the address part to choose which address to
use for the socket. This way there can be different programs listening on
different addresses but using the same port. Also one may wish to limit
listening socket's visibility to localhost in some cases.

Both incoming and outgoing sockets can use bind in exactly the same manner,
and the functionality is the same, choose which local address and port the
socket uses. Then the server calls =listen()= to make it an incoming one, and
client calls =connect()= to dial into remote host.

(Assuming tcp here, partially applies to udp to disregarding the
=listen()/connect()= part, unix sockets don't use bind on client side.

Also, while server side usually binds, it is not always necessary; the port
will be random, but the number can be obtained with =getsockname()=. This can be
useful for opening side channels (like actual file transfers in ftp, or IRC
DCC); or if there's some other way for service discovery beside constant port.

-> Truth. The server can instead rely on broadcasting or listening for
   broadcasts to start communication, although relying on a specific port is
   still generally more common.

--- 

When you bind a socket, you are essentially telling the kernel that you want
to listen for connections on that specific port number, so think of it as a
resource reservation.

First the =bind()= function takes two arguments; the address of the socket and
the port number. Working with that information, we can deduce that the =bind()=
function creates a listening socket on a server.

You typically bind on the server as the client's kernel will perform this for
you.

[[https://www.reddit.com/r/C_Programming/comments/1534wup/questions_about_binding_in_sockets_programming/]]
